language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: required # weird problem with 'ping' in docker
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      sudo: required
    - os: osx
      osx_image: xcode8.2
      latex: false
      env: _R_CHECK_FORCE_SUGGESTS_=FALSE
    - os: osx
      osx_image: xcode7.3
      latex: false
      env: _R_CHECK_FORCE_SUGGESTS_=FALSE
    - os: osx
      osx_image: xcode6.4
      latex: false
      r: oldrel
      env: _R_CHECK_FORCE_SUGGESTS_=FALSE

addons:
  apt:
    packages:
      - iputils-ping
      - libapparmor-dev